In [ ]:
# 1. Створити одновимірний масив (вектор) з першими 20-ма натуральними числами та вивести його значення.
import numpy as np

arr1 = np.arange(1, 21)
print("Завдання 1")
print(arr1)

# 2. Створити двовимірний масив (матрицю) розміром 4x4, заповнити його одиницями та вивести його значення.
arr2 = np.ones((4, 4))
print("Завдання 2")
print(arr2)

# 3. Створити масив розміром 5x5, заповнити його випадковими дійсними числами в діапазоні від -1 до 1 та вивести його значення.
arr3 = np.random.uniform(-1, 1, (5, 5))
print("Завдання 3")
print(arr3)

# 4. Створити масив розміром 3x3, заповнити його випадковими дійсними числами в діапазоні від 0 до 1 та вивести його значення.
arr4 = np.random.rand(3, 3)
print("Завдання 4")
print(arr4)

# 5. Створити два одновимірних масиви розміром 6, заповнити їх випадковими цілими числами в діапазоні від 1 до 20 та виконати на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1, 21, 6)
b = np.random.randint(1, 21, 6)

print("Завдання 5")
print("a =", a)
print("b =", b)

print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)

# 6. Створити дві матриці розміром 3x2 та 2x4, заповнити їх випадковими цілими числами в діапазоні від 1 до 5 та перемножити їх між собою.
m1 = np.random.randint(1, 6, (3, 2))
m2 = np.random.randint(1, 6, (2, 4))

print("Завдання 6")
print("m1 =\n", m1)
print("m2 =\n", m2)

result6 = np.dot(m1, m2)
print("Добуток =\n", result6)

# 7. Створити матрицю розміром 3x3, заповнити її випадковими дійсними числами в діапазоні від 0 до 1 та транспонувати її.
m3 = np.random.rand(3, 3)

print("Завдання 7")
print("Початкова матриця =\n", m3)
print("Транспонована матриця =\n", m3.T)

# 8. Створити дві матриці розміром 3x3, заповнити їх випадковими цілими числами в діапазоні від 1 до 10 та знайти їхню різницю.
m4 = np.random.randint(1, 11, (3, 3))
m5 = np.random.randint(1, 11, (3, 3))

print("Завдання 8")
print("m4 =\n", m4)
print("m5 =\n", m5)

print("Різниця =\n", m4 - m5)

# 9. Створити дві матриці розміром 3x3, заповнити їх випадковими цілими числами в діапазоні від -5 до 5 та знайти їх добуток.
m6 = np.random.randint(-5, 6, (3, 3))
m7 = np.random.randint(-5, 6, (3, 3))

print("Завдання 9")
print("m6 =\n", m6)
print("m7 =\n", m7)

print("Добуток =\n", np.dot(m6, m7))

# 10. Створити матрицю розміром 3x3, заповнити її випадковими дійсними числами в діапазоні від -1 до 1 та знайти вектор-стовпчик, що містить суму елементів кожного рядка матриці.
m8 = np.random.uniform(-1, 1, (3, 3))

print("Завдання 10")
print("Матриця =\n", m8)

row_sums = np.sum(m8, axis=1).reshape(-1, 1)
print("Вектор-стовпчик сум =\n", row_sums)

Завдання 1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Завдання 2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Завдання 3
[[ 0.7326476  -0.13525335 -0.22369051 -0.46975641  0.93724767]
 [ 0.7790882  -0.40051442 -0.25208595  0.0589521   0.39570234]
 [-0.16967669  0.41905888  0.61277657  0.88217038  0.32477439]
 [ 0.04319327 -0.20955249  0.6969305  -0.73204674 -0.93262971]
 [ 0.40169741  0.00908077  0.14878128 -0.22364237  0.42422973]]
Завдання 4
[[0.54002744 0.28124896 0.04864643]
 [0.29882599 0.13357918 0.22247187]
 [0.68221675 0.28217047 0.21021925]]
Завдання 5
a = [ 1  9  8 17 17  5]
b = [13 12  7  3  3  4]
Додавання: [14 21 15 20 20  9]
Віднімання: [-12  -3   1  14  14   1]
Множення: [ 13 108  56  51  51  20]
Завдання 6
m1 =
 [[5 2]
 [4 5]
 [3 4]]
m2 =
 [[2 4 3 4]
 [2 1 5 1]]
Добуток =
 [[14 22 25 22]
 [18 21 37 21]
 [14 16 29 16]]
Завдання 7
Початкова матриця =
 [[0.22990776 0.61461024 0.04517207]
 [0.76415811 0.94455755 0.06480534]
 [0.53159891 0.